# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to='photos', verbose_name='Please upload Photo')),
            ],
        ),
    ]
