# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 23:55
from __future__ import unicode_literals

from django.db import migrations
import webcam.fields
import webcam.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webcamapp', '0002_auto_20160405_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=webcam.fields.CameraField(blank=True, null=True, storage=webcam.storage.CameraStorage(), upload_to='/static/images', verbose_name='Please upload Photo'),
        ),
    ]
