# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcamapp', '0005_auto_20160406_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoperson',
            old_name='camera',
            new_name='picture',
        ),
    ]
